site_name: SCUBAS Documentation
repo_url: https://github.com/shibaji7/SCUBAS
theme: readthedocs
markdown_extensions:
    - extra
    - admonition
    - toc

nav:
    - Home: index.md
    - Installation: user/install.md  
    - INTERMAGNET Data Access: user/intermagnet.md 
    - Citing: user/citing.md
    - Tutorials: dev/scubas.md
    - Code Documentation:
            - Cables: dev/cables.md
            - Ocean/Earth Conductivity: dev/conductivity.md
            - Datasets: dev/datasets.md
            - Ocean/Earth Model: dev/models.md
            - Plotting Library: dev/plotlib.md
            - Utility Module: dev/utils.md