site_name: SCUBAS Documentation
repo_url: https://github.com/shibaji7/SCUBAS
theme: 
  name: "material"
plugins:
    - search
    - mkdocstrings:
        enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
        custom_templates: templates
        default_handler: python
        handlers:
          python:
            options:
              show_source: true
     
markdown_extensions:
    - extra
    - admonition
    - toc
    - attr_list
    - pymdownx.arithmatex:
        generic: true
        

nav:
    - Home: index.md
    - Installation: user/install.md  
    - INTERMAGNET Data Access: user/intermagnet.md 
    - Citing: user/citing.md
    - Tutorials: 
            - TLM Theory: tutorial/theory.md
            - Long and Short Cables: tutorial/elsc.md
            - Active Termination: tutorial/active.md
            - Network Modeling: tutorial/netmodel.md
            - Case Studies/Codes: tutorial/conduct.md
            - Event Study (1989 Strom): tutorial/1989.md
    - Code Documentation:
            - Cables: dev/cables.md
            - Ocean/Earth Conductivity: dev/conductivity.md
            - Datasets: dev/datasets.md
            - Ocean/Earth Model: dev/models.md
            - Plotting Library: dev/plotlib.md
            - Utility Module: dev/utils.md